<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Citizen;
use App\Models\Family;
use App\Models\Dusun;
use Faker\Factory as Faker;
use Carbon\Carbon;

class PopulationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->command->info('Membuat data Keluarga dan Penduduk...');
        
        $faker = Faker::create('id_ID');
        
        // Ambil dusun yang sudah ada
        $dusuns = Dusun::all();
        
        if ($dusuns->isEmpty()) {
            $this->command->error('Tidak ada data Dusun! Jalankan VillageProfileSeeder terlebih dahulu.');
            return;
        }

        $jobs = ['Petani', 'PNS', 'Wiraswasta', 'Karyawan Swasta', 'Buruh Harian Lepas', 'Mengurus Rumah Tangga', 'Pelajar/Mahasiswa', 'Belum/Tidak Bekerja'];
        $educations = ['SD / Sederajat', 'SMP / Sederajat', 'SMA / Sederajat', 'D1 / D2 / D3', 'D4 / S1 / Profesi', 'Tidak Punya Ijazah SD'];
        $jobStatuses = ['Berusaha Sendiri', 'Buruh / Karyawan / Pegawai Swasta', 'Pekerja Bebas', 'Pekerja Keluarga / Tidak Dibayar', 'ASN / TNI / Polri / BUMN / BUMD / Pejabat Negara', 'Berusaha Dibantu Buruh', 'Lainnya'];
        $assistanceTypes = ['PKH', 'BPNT', 'BLT Desa', 'Subsidi Listrik', 'Tidak Ada'];

        for ($i = 0; $i < 20; $i++) {
            $dusun = $dusuns->random();
            $rt = str_pad(rand(1, $dusun->total_rt), 3, '0', STR_PAD_LEFT);
            $rw = str_pad(rand(1, $dusun->total_rw), 3, '0', STR_PAD_LEFT);
            $headGender = rand(0, 1) ? 'male' : 'female';
            $headName = $faker->name($headGender);
            
            // Generate NIK (16 digits) and KK (16 digits)
            $kkNumber = $faker->numerify('7307##########');
            $headNik = $faker->numerify('7307##########');

            // 1. Buat Keluarga
            $family = Family::create([
                'kk_number' => $kkNumber,
                'head_name' => $headName,
                'head_nik' => $headNik,
                'address' => $faker->streetAddress,
                'dusun_id' => $dusun->id,
                'rt' => $rt,
                'rw' => $rw,
                'address_matches_kk' => 1,
                'family_member_count' => rand(2, 5),
                'assistance_type' => $faker->randomElement($assistanceTypes),
                'building_type' => $faker->randomElement(['Rumah Tinggal Tunggal', 'Rumah Susun', 'Lainnya']),
                'ownership_status' => $faker->randomElement(['Milik Sendiri', 'Sewa / Kontrak', 'Bebas Sewa', 'Dinas']),
                'floor_area' => rand(30, 150),
                'electricity_power' => $faker->randomElement(['450 VA', '900 VA', '1300 VA', '2200 VA', 'Tanpa Listrik']),
                'water_source' => $faker->randomElement(['Sumur Bor / Pompa', 'Sumur Terlindung', 'Leding', 'Mata Air', 'Air kemasan bermerek']),
                'toilet_facility' => $faker->randomElement(['Milik Sendiri', 'Bersama', 'MCK Umum', 'Tidak Ada']),
                'notes' => 'Generated by Seeder',
            ]);

            $headEdu = $faker->randomElement($educations);
            // 2. Buat Kepala Keluarga
            Citizen::create([
                'nik' => $headNik,
                'dusun_id' => $dusun->id,
                'family_id' => $family->id,
                'kk_order' => 1,
                'name' => $headName,
                'place_of_birth' => $faker->city,
                'date_of_birth' => $faker->dateTimeBetween('-60 years', '-30 years')->format('Y-m-d'),
                'gender' => $headGender == 'male' ? 'Laki-laki' : 'Perempuan',
                'religion' => 'Islam',
                'education' => $headEdu,
                'education_level' => $headEdu,
                'job' => $faker->randomElement($jobs),
                'job_status' => $faker->randomElement($jobStatuses),
                'marital_status' => 'Kawin',
                'family_relation' => 'Kepala Keluarga',
                'citizenship_status' => 'Tinggal di Rumah Ini',
                'status' => 'Aktif',
                'blood_type' => $faker->randomElement(['A', 'B', 'AB', 'O', 'Tidak Tahu']),
                'has_income' => 1,
            ]);

            // 3. Buat Istri / Suami (tergantung Kepala Keluarga)
            $spouseGender = $headGender == 'male' ? 'female' : 'male';
            $spouseNik = $faker->numerify('7307##########');
            
            $spouseEdu = $faker->randomElement($educations);
            Citizen::create([
                'nik' => $spouseNik,
                'dusun_id' => $dusun->id,
                'family_id' => $family->id,
                'kk_order' => 2,
                'name' => $faker->name($spouseGender),
                'place_of_birth' => $faker->city,
                'date_of_birth' => $faker->dateTimeBetween('-55 years', '-25 years')->format('Y-m-d'),
                'gender' => $spouseGender == 'male' ? 'Laki-laki' : 'Perempuan',
                'religion' => 'Islam',
                'education' => $spouseEdu,
                'education_level' => $spouseEdu,
                'job' => 'Mengurus Rumah Tangga',
                'job_status' => 'Lainnya',
                'marital_status' => 'Kawin',
                'family_relation' => $headGender == 'male' ? 'Istri' : 'Suami',
                'citizenship_status' => 'Tinggal di Rumah Ini',
                'status' => 'Aktif',
                'blood_type' => $faker->randomElement(['A', 'B', 'AB', 'O', 'Tidak Tahu']),
                'has_income' => rand(0, 1),
            ]);

            // 4. Buat Anak
            $childrenCount = $family->family_member_count - 2;
            for ($j = 0; $j < $childrenCount; $j++) {
                $childGender = rand(0, 1) ? 'Laki-laki' : 'Perempuan';
                $childNik = $faker->numerify('7307##########');
                $isAdult = rand(0, 1);
                
                $childEdu = $isAdult ? $faker->randomElement($educations) : 'SD / Sederajat';
                Citizen::create([
                    'nik' => $childNik,
                    'dusun_id' => $dusun->id,
                    'family_id' => $family->id,
                    'kk_order' => $j + 3,
                    'name' => $faker->name($childGender == 'Laki-laki' ? 'male' : 'female'),
                    'place_of_birth' => $faker->city,
                    'date_of_birth' => $isAdult 
                        ? $faker->dateTimeBetween('-24 years', '-18 years')->format('Y-m-d')
                        : $faker->dateTimeBetween('-17 years', '-5 years')->format('Y-m-d'),
                    'gender' => $childGender,
                    'religion' => 'Islam',
                    'education' => $childEdu,
                    'education_level' => $childEdu,
                    'job' => $isAdult ? $faker->randomElement($jobs) : 'Pelajar/Mahasiswa',
                    'job_status' => $isAdult ? $faker->randomElement($jobStatuses) : 'Lainnya',
                    'marital_status' => 'Belum Kawin',
                    'family_relation' => 'Anak',
                    'citizenship_status' => 'Tinggal di Rumah Ini',
                    'status' => 'Aktif',
                    'blood_type' => $faker->randomElement(['A', 'B', 'AB', 'O', 'Tidak Tahu']),
                    'has_income' => $isAdult ? 1 : 0,
                ]);
            }
        }

        $this->command->info('Berhasil menyuntikkan 20 Data Keluarga dan anggota keluarganya.');
    }
}
